import {
    BsUmbrellaFill,
    BsFillMusicPlayerFill,
    BsMusicNoteBeamed,
    BsStarFill,
    BsTrophyFill,
    BsSuitHeartFill,
    BsFillHandThumbsUpFill,
    BsFillEmojiSunglassesFill,
    BsFillDropletFill,
    BsFillBrightnessHighFill,
    BsMoonFill,
    BsMicFill,
    BsEmojiWinkFill,
    BsPersonBoundingBox,
    BsFillAwardFill,
} from 'react-icons/bs'
export const categories = [
    { name: '윤하', icon: <BsUmbrellaFill /> },
    { name: '이바다', icon: <BsFillMusicPlayerFill /> },
    { name: '소각소각', icon: <BsMusicNoteBeamed /> },
    { name: '윤딴딴', icon: <BsStarFill /> },
    { name: '태연', icon: <BsTrophyFill /> },
    { name: '헤이즈(Heize)', icon: <BsSuitHeartFill /> },
    { name: '성시경', icon: <BsFillHandThumbsUpFill /> },
    { name: '나얼', icon: <BsFillEmojiSunglassesFill /> },
    { name: '박효신', icon: <BsFillDropletFill /> },
    { name: '규현', icon: <BsFillBrightnessHighFill /> },
    { name: '정상수', icon: <BsMoonFill /> },

    { name: '아이유', icon: <BsMicFill /> },
    { name: '멜로망스', icon: <BsEmojiWinkFill /> },
    { name: '치즈(CHEEZE)', icon: <BsPersonBoundingBox /> },
    { name: '김경호', icon: <BsFillAwardFill /> },
]
